---
# tasks file for roles/database
- name: Remove old database container
  command: docker rm -f database
  ignore_errors: yes
  
- name: Run database container
  command: >
    docker run -d
    --name database
    --network app-network
    -e POSTGRES_USER={{ POSTGRES_USER }}
    -e POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
    -e POSTGRES_DB={{ POSTGRES_DB }}
    bouafou/tp-devops-database
  ignore_errors: yes
