services:
  backend:
    build: ./simpleapi
    networks:
      - app-network
    depends_on:
      - database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  database:
    build: ./postgre
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  httpd:
    build: ./serveur
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8080/

networks:
  app-network:

volumes:
  pgdata: