name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true
          no-cache: true

  build-and-push-database:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./postgre
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true
          no-cache: true
  build-and-push-httpd:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./serveur
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true
          no-cache: true

  deploy:
    runs-on: ubuntu-24.04
    needs:
      - build-and-push-backend
      - build-and-push-database
      - build-and-push-httpd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan marie.bouafou.takima.school >> ~/.ssh/known_hosts

      - name: Deploy with Ansible
        run: ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml -v
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"